# Generated by Django 2.2.3 on 2019-07-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190722_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
