# Generated by Django 2.2.3 on 2019-08-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='send_msg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
