# Generated by Django 2.2.3 on 2019-08-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190804_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='career',
        ),
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
