# Generated by Django 2.2.3 on 2019-08-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190804_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='career',
            new_name='description',
        ),
    ]
