# Generated by Django 2.2.3 on 2019-08-05 00:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usereducation_userexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_filename_path),
        ),
    ]
