# Generated by Django 2.2.4 on 2019-09-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190805_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('bs', 'Basic'), ('bl', 'Blogger')], default='bs', max_length=2),
        ),
    ]
