# Generated by Django 2.2.6 on 2019-11-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190928_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MySite',
                'verbose_name_plural': 'MySites',
            },
        ),
    ]
