version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
      - /media:/media
    depends_on:
      - web

  db:
    image: postgres:latest

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  web:
    restart: always
    build: .
    volumes:
      - ./tuexperto:/code
      - ./tuexperto/static:/static
      - ./tuexperto/media:/media
    command: bash -c "python /code/manage.py makemigrations --no-input && python /code/manage.py migrate --no-input && gunicorn tuexperto.wsgi -b 0.0.0.0:8080 --reload"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A tuexperto worker -l info
    volumes:
      - ./tuexperto:/code
    depends_on:
      - db
      - redis
      
  celery-beat:
    build: .
    command: celery -A tuexperto beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./tuexperto:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
