# Generated by Django 2.2.3 on 2019-07-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190710_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('pg', 'page'), ('pt', 'post')], default='pt', max_length=2),
        ),
    ]
