# Generated by Django 2.2.3 on 2019-07-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_in_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
