# Generated by Django 2.2.6 on 2019-10-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190719_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('pg', 'page'), ('pt', 'post'), ('co', 'course')], default='pt', max_length=2),
        ),
    ]
